### ISSUE TITLE
New release planned ?

### ISSUE THREAD

**Issue by obazoud** [sensu-plugins/sensu-plugins-zookeeper#4]
Is a new release planned any time soon for this plugin ?
That last release was in December 2015 and check-zookeeper-ruok.rb has been added since then which would be very useful for us.

**Comment by eheydrick** [comment]
Yes, will cut a new release soon.

**Comment by lymichaels** [comment]
+1 would like to use the new check!

**Comment by obazoud** [comment]
@eheydrick any update ?

**Comment by eheydrick** [comment]
I took a look at the releases and turns out [0.1.0](https://rubygems.org/gems/sensu-plugins-zookeeper/versions/0.1.0) was released in March and it includes `check-zookeeper-ruok.rb`. Somehow the tag was never created. I'll get that fixed up.

**Comment by eheydrick** [comment]
I tagged [0.1.0](https://github.com/sensu-plugins/sensu-plugins-zookeeper/releases/tag/0.1.0).
